name: Release
on:
  workflow_dispatch:

permissions:
  packages: write
  pull-requests: write
  contents: write
  issues: write
  id-token: write
  attestations: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      # - name: Test
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: Zip dist
        run: zip -r dist.zip dist

      - name: Attest
        uses: actions/attest-build-provenance@v1.4.3
        with:
          subject-path: |
            defaults/**/*
            dist/**/*
            templates/**/*
            LICENSE
            README.md
            package.json

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dist
          path: dist.zip
